### ISSUE TITLE
Highlight selected text: URGENTish

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#103]
Blake added a ripper select text feature, you can highlight a sting of text and get a pasteable URL, which will show the text with highlight. But this has been broken for several months now, we need it back!

A cooler implementation would offer a popup when you highlight the text, similar to the "quote" thingy on Discourse.

**Comment by sujato** [comment]
Also, use JS for copying, no flash!

https://github.com/zenorocha/clipboard.js

**Comment by blake-sc** [comment]
Done in aa38937, clipboard.js seems to work great.
