### ISSUE TITLE
Reduce heading levels in ToC

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#105]
Restrict ToC in sidebar to max depth of `<h4>`. Currently, excessively long ToCs are found in some texts.

**Comment by ghost** [comment]
I have reduced the headings in the doMenu function in sidebar.js to limit h2,h3.h4.
If this has an unwanted effect elsewhere, please undo my commit.

**Comment by sujato** [comment]
Looks good, we can close this.
