### ISSUE TITLE
HTML to LaTeX and Print on Demand

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#109]
Scripted conversion from SuttaCentral's HTML to LuaLaTeX for creation of high-quality pdfs for viewing and printing. Also, provide a service for automatic creation of high quality books for reading.

HTML to LaTeX conversion is hard to do well, as the languages are conceptually different. However, given the simple, standardized, and predictable nature of SC's HTML5 text markup, it should be possible to write a simple script to do basic conversion.

I've now produced a nice version of the Theragatha on Lulu using LaTeX. Even the hardcover is pretty good these days!

I have created a LaTeX cover file, too, which is pretty sweet and could be auto-produced from SC. The relevant files for book and cover are in /design.

It may not be relevant, but CSS3 has quite good support for producing books straight from HTML/CSS, including things like page headers, margins, and even footnotes. 

http://www.smashingmagazine.com/2015/01/07/designing-for-print-with-css/

We won't be printing straight from HTML, but I'm wondering whether any of these ideas might provide a conceptual bridge for linking the HTML/CSS world with LaTeX.

Some issues with producing books.
1. We will need to redo the heading information, generally only including the info in the `<h1>`. 
2. One of LaTeX's features is to _not_ get everything right; it leaves difficult bits to be hand fixed. We'll need to find a way around this. (perhaps check how Wikipedia does it.)
3. Author and Title info should be added to the header.
4. Back cover blurbs could be derived from the "Description".
5. Different texts will need different handling. For example, in DN and MN we could make each sutta a chapter, but this wouldn't work for AN and SN. For Dhp, the chapter will be on the vagga. We will need to set up the conversion template specifically for each division or subdivision.
6. Do we produce a separate book for each text in KN? Kp will be too small.
7. It is possible to produce books in various formats: large print for readers with poor eyesight, small size for portability. It is even possible to allow readers to select their own text and create custom compilations; although this will be more complex.
8. As well as the translations, it would be good to do a proper printed edition of the Pali text. We could even do this in multiple scripts. we'd need to ensure proper pali/Sanskrit hyphenation, which is available for LaTeX. Possibly we could do the other original language texts as well.
9. The SC pali text has variant readings. It would be possible to print these as footnotes.
10. We would need to decide what reference information to include. For the Thag, I have included the verse numbers as marginal notes (using, of course, the correct script numerals!). 
11. In the longer term, I'd like to look at producing a high-quality hardcover edition for reading, modeled after the Bibliotheca project: https://www.kickstarter.com/projects/530877925/bibliotheca
12. As for the translations, it would definitely be a good idea to produce these books in the various languages we host. Copyright issues aside, it should be be difficult in principle, given the wide i18n support on LaTeX, and the consistency of our HTML files. But we should also bear in mind the quality of translations, degree of completeness, and support from native language speakers. In addition, there are several cases where the printed edition is already available, such as Thai, Sinhala, Hindi, and Indonesian. I think this should be handled on a case by case basis: select a language, and work with the native language speakers to ensure a good output. This would involve detailed checking of the translation, and proofreading. In this way we offer to the translators the possibility of creating a high quality printed edition of their work, while we benefit from improving the quality of the text on SC.
13. On a related note, should this be "Make LaTeX on demand", or should we prepare the files beforehand? Given the various issues, I suspect the latter may be better. Of course, the update process needs to be painless. Perhaps we could develop a specific variant of the HTML2LaTeX template for each division, test it well, then deploy when we know it works. 
## Some more details

Doing the markup for LaTeX is trivial; the hard part is getting all the formatting and details for the text right, but I've already done that; it's just imported as a "head", much the same as the HTML `<head>.`

The tricky bits will be in organizing the different texts so that they make sense within a book format.
### Basic transformations

Most things can be more or less one-to-one changed:

```
<em> and <i> ---> \emph
<strong> and <bold> --->\textbf
class="smallcaps" ---> \textsc
<h1> ---> \chapter (but see below)
<h2>, <h3, <h4>, etc ----> \section, \subsection, \subsubsection...
<p> ---> double line break
<blockquote class="gatha"> ----> something for verses, can't recall off the top of my head
<ul> ---> \itemize
<ol> ---> \enumerate
```

You can also easily make little macros in LaTeX with arbitrary names that can correspond with your CSS classes. So, for example, we might have `<p class="end">` and we just create a LaTeX command \end, with appropriate styling. (Except we can't use "end" 'cos it's needed by LaTeX, so use "fin" or something instead.)
### Adapt for book:

How to organize the texts:
- For MN and DN, create three books each.
- For DN, sutta = \chapter.
- For MN, vagga = \chapter, and sutta = \section (or could do as for DN)
- For SN, make 5 books. Each Big Vagga = book. Samyutta = \part, small vagga = \chapter, sutta = \section
- For AN, make 5 or 6 books. Two or three nipatas = one book; nipata = \part, vagga = \chapter, sutta = \section
- For KN, make each text one book (what to do with KP?)

We can pull information such as translator, header info, title, and the like from the appropriate place in each text. However it will probably be useful to put these in an interim format (JSON?) which can be edited by hand before use in LaTeX to tweak the details. For example, we might have two authors for a text; in the HTML these might be "Author one, Author Two", but we probably want to say "Author One & Author Two". 

Anyway, enough for now, but hopefully you can see how this can happen. As for getting it working on the back end, we can see how Wikipedia does it. Also, a contributer to my blog runs [Lapis Lazuli Texts](http://lapislazulitexts.com/tripitaka), and he has already implemented a LaTeX backend, so we can consult with him.

**Comment by ghost** [comment]
I have made a little python script to convert the html texts into latex. Still need some tweeking with regards to fonts, styling etc. but sofar does well on the DN (except for omitting all pali characters). 
Thank you Bhante for sending those files and tips on fonts - this will make it a lot easier.

I have some questions about the requirements:
1. You want to have 3 books for MN and DN, 5 for SN, etc. What is the reason for dividing it up like this? Some languages do not have all the suttas in a nikaya so it would not make sense to have 4 suttas divided into 3 books for instance. The german SN is for instance divided into 3 books by 3 different authors. How to deal with such cases?
2. Metaareas can differ per sutta - how do we deal with this (I think copyright info would need to be included in the book too)?
3. Will users be able to also just publish one sutta instead of the whole book? 

No doubt more questions will come up in due time but this will do for now.

**Comment by sujato** [comment]
Wow, thanks I'll have a look at this soon. But quickly:
1. Each case will have to be treated differently. I don't think we should be making books out of every collection we have on SC. But the basic idea should be modelled after the Pali.
2. With metadata it needs to be handled carefully. I would prefer to concentrate on those collections with a single author for now. 
3. I doubt it. In the future we may have personally selected texts, but to begin with i think we should curate selected editions based on quality, complteness, and need (in many cases there are already printed editions.)

**Comment by ghost** [comment]
Just so I get this right:
Do you want to just make some pdf books of selected texts and then upload those pdf's to the server so people can download them from the website or do you want the server to compile books 'on demand'?

The former is of course fairly easy to do and we can start with that, but with a python script behind it the "on demand" option should be possible too (you can just omit the possibility for the texts where copyright is a problem but some authors just make translations in order to spread the Dhamma and would love to see their work published in that way).

BTW I got LuaLaTeX working now.

**Comment by sujato** [comment]
I think initially we should focus on producing curated pdfs and making them available as books. One of the conceptual differences between LaTeX and HTML is that LaTeX is meant for things that take time, and are prepared beforehand, not for things that are made on the fly. So it deliberately fails on some points where the code can't work out the best solution. Sure, we could work our way around this problem, but that's not the point. The point is, that's what it's meant to do, and for good reason.

If we can automate the process as much as possible, then finalize by hand, we can move towards being able to make pdfs fully automated on demand. That will, however, create a whole bunch of other problems, depending how much freedom we give to people to make what they want. 

One problem with preparing the files beforehand is, what happens if we update them? We should have a trigger in the system, so that if we update a certain HTML file, when the TIM adds it it checks whether we have a pdf of that text; if so, it informs us that we need to update the pdf, or if possible, it updates it automatically.

**Comment by ghost** [comment]
From email 22/7/2015:
We will prepare the Portugese texts as a pilot program. After that the pali, which should be fairly consistent also with the new English translations that Bhante will make in the next 18 months.
The first task will be to successfully produce PDFs from the files we have. Ultimately I'd like to publish them on Lulu.com, and for free distribution. Eventually, you might even be able to select the suttas you like on SC, and create a custom book; but this will take a little while. In addition to PDF, we should also create EPUBs for ebook readers, which are very popular these days. This is, however, much easier, as EPUB is basically just HTML in a wrapper.

**Comment by aminah-sc** [comment]
Subsumed within the new, broader "PO to print" epic (https://github.com/suttacentral/suttacentral/issues/960).
