### ISSUE TITLE
Reorganize Tibetan texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#112]
In accord with this:

https://github.com/suttacentral/suttacentral/wiki/04.11-Tibetan-text-sites#how-to-organize-tibetan-texts

And as discussed and agreed with John and Rod, we should reorganize our Tibetan texts so as to have only the Derge/Peking division, and the Upayika.

Ayya Dhammadinna is working on the Upayika and results should be available in due course.

**Comment by ghost** [comment]
Has moved to 
https://github.com/suttacentral/old-wiki/wiki/04.11-Tibetan-text-sites

**Comment by sujato** [comment]
Bump! make sure that this is implemented in our new version @blake-sc @SamaneriVimala
