### ISSUE TITLE
Pali text with section numbers for DN and MN

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#113]
A couple of months ago, Ven KB finished adding the section numbers for DN and MN. This should be used for the Pali text for these two texts.

**Comment by yapcheahshen** [comment]
I believe section numbers can be retrieved by a.sc[id="n"]
do you have plan to apply the same id to other version of Tripitaka and translations ?

**Comment by sujato** [comment]
So the update mentioned here is where a monk has gone through the Pali text and added the same numbers used in the English translation. This isn't a trivial exercise.

More generally, it would be great to coordinate editions, but not easy to to. The main plan will be when the PO translations start being made, then the texts will automatically linked segment by segment. Everything will have the same refs as in the Pali text. Until then, each edition is separate (although in fact they often have things in common; many editions, for example, adopt the PTS chapter and section numbers for DN).

**Comment by yapcheahshen** [comment]
Just out of curiosity, do you need to check other edition of Pali text when doing translation? if so, segment alignment is useful.

Since you already have semantic segments, maybe we can try to segment other edition of Pali text by machine, I believe that most of the content are identical and in same sequence.

**Comment by sujato** [comment]
I won't be doing detailed checking of other editions, as my translation is intended to be a general purpose translation of the Mahasangiti text. I'll only be checking variants when the mainline text is unclear.

Machine alignment of other editions will surely be possible, as the variants between editions are mostly trivial. The only major obstacle will be the different handling of abbreviations and such. But that will only affect a small percentage of the text. I would expect we could do 95% automatically, then the rest by hand.

**Comment by sujato** [comment]
This has now been implemented by Blake.
