### ISSUE TITLE
What's new on SC link on home page

### ISSUE THREAD

**Issue by palistudent** [suttacentral/legacy-suttacentral#120]
What I am proposing is a link on the home page that says something like "What's new on Sutta Central?" - just one simple clickable line of text. When clicking on that the user then goes to a separate page that lists latest enhancements, most recent first. E.g.,

```
        28 May, 2015
                    There is now an advanced search tool, find it at ….
                    It permits making more precise queries and also searching on fields such as PTS Vol/Page.
                    blah blah ….

        xx April, 2015
                    Russian translations of blah blah blah have now been added.

        etc.
```

When a user has visited this page s/he will no longer see the link on the home page, until such time as some new enhancement to site has been added to top of enhancement list page, then the trigger for display of link is reset.  All very clean. Most of the time home page will look just as it does now, and only when there is an important announcement will it change slightly, and temporarily.

**Comment by ghost** [comment]
@palistudent: Everything that is new is posted on the Updates in Discourse. There is a link on the SC homepage at https://suttacentral.net/about with a link to what's new. It says: SuttaCentral is under heavy development and updates are made regularly. To keep up with what’s new, check the Updates category in our forum.
