### ISSUE TITLE
Bengali texts

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#121]
As per email of 20/7/2015:
Ven Karunabangsha Bhikkhu (Kbangsha Bhante): has a long term project to prepare the Bengali translations of the Pali canon in a digital form. 

It will take some time but the Venerable is working on making the files in Unicode for us. 
A new issue will be made for each part of the project.
Sofar he has only sent the Tha-ap and Thi-ap.

**Comment by aminah-sc** [comment]
Issue moved to [suttacentral/suttacentral suttacentral/sc-data#260](https://github.com/suttacentral/sc-data/issues/260) via [**ZenHub**](https://www.zenhub.com/)
