### ISSUE TITLE
Hindi texts

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#126]
From email 21/7/2015:
Dilbag: Has been helping with Hindi texts. He is a new samanera at Bodhinyana. He has a good knowledge of what texts are available in Hindi, and what has been done. When I arrive back at Bodhinyana I will make a master list with him of what remains to do. But basically we have had typed the Suttas and Vinaya, and much of that still needs to be prepared for SC.

The typing has been done by two firms in India:
Alpesh: alpesh.raval@hitechbpo.com
Shikha: shikha.panjwani@edatamine.com
Both have been excellent to work with, but if any more work is needed, Shikha and her team have been faster and more pro-active. However I think that we have finished on that side, and the main work that remains is for us.

So the task from here is to get texts in a reasonable form, with numbering of suttas according to SC, and work with Ayya Vimala to prepare the HTML for SuttaCentral.

**Comment by sujato** [comment]
This is still outstanding. We have a number of Hindi texts typed and ready to go, but we need to number and mark them up. We need a volunteer who knows Hindi and suttas. maybe try Dilbag again.

**Comment by ghost** [comment]
I have emailed Dilbag twice last year but no reply. Does he have another email now?

**Comment by sujato** [comment]
I don't know. In any case, he probably won't be checking email much if at all during the vassa. Let's leave this for now and get back to it then.

**Comment by aminah-sc** [comment]
Duplicated
