### ISSUE TITLE
Contacts/people page update

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#127]
Since the page is now a lot longer than it was originally conceived as, there are problems with things like sorting and so on. Probably the best thing to do would be to convert the main list into a CSV file with three columns (Name, Description, Comments; the last would not be displayed and can be normally empty.) Then we pull the data from there and sort when the page is called.

One more detail, actually it shouldn't be called the contacts page, it has long outgrown that. It would be better to rename it "people.html" and ensure that the renaming is handled consistently.

**Comment by sujato** [comment]
Please go ahead with these changes, and also add anyone you think should be added!

**Comment by ghost** [comment]
I'll start on this.

**Comment by ghost** [comment]
I updated the people's page i.e. added new people, sorted by name, made into JSON lib (not really needed but good exercise for me) and made the descriptions a bit more consistent.
