### ISSUE TITLE
Language drop-down menu

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#129]
The language drop-down menu needs to change to show the author with the language as a mouse-over rather than the other way around as it is now.

**Comment by sujato** [comment]
This comes within the wider scope of some other issues, including i18n and improving translator visibility.

We also need to implement a systematic way of handling multiple translations per language, especially when my translations are ready. In such a case we would probably do something like:
- en Bodhi
- en Sujato
- en Anandajoti
- nl Vimala
- hu Blake

But the details need to be carefully thought through. One complexity is that we don't always know the translator, so sometimes we will have to default to the language.
