### ISSUE TITLE
Implement exotic scripts in multi-language contexts as SVGs

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#130]
We have somewhat of a display problem in showing multiple languages in drop down menus, the Pali font-switcher, etc; in general in any context where there are multiple languages on one page. We can't deliver all the fonts required (because it would be a huge download for just a few characters), and some computers don't have all the glyphs necessary, so you get tofu.

The best solution for this will, I suggest, be to use SVGs. That way we can get scalable versions of all the glyphs we want, using the right fonts and so on.

**Comment by blake-sc** [comment]
SVG doesn't sound look a good solution to me. I think the best approach would be to use fontTools to create subsets of the fonts required, and then merge the subsets into a new font. Call that the "menu" font. This could be automated from a simple config saying what text to extract from what fonts and be part of the automatic assets compilation. I have also considered, as an anti-FOUT technique, encoding certain fonts directly into the compiled CSS, for example as a WOFF font "☸SutaCenrl' takes 4.1kb (3.0kb if hinting is removed), as a plain SVG the text "☸SuttaCentral" takes 13.7b (2.7kb once optimized and gzipped). So if a font is used for only one small stretch of text the size of a dedicated font and the size of a SVG are nearly identical. The font though, has the advantage of fontiness, that is the text remains actual text that is bound by all the rules of CSS, and isn't just a bunch of curves. The one disadvantage of fonts, the proliferation of formats, would be mitigated by going with 100% WOFF.
I suppose the only thing SVG does well is it works even in browsers which simply do not support @font-face, although if the browser is genuinely unable to render the font the user also wont have any joy at the destination of the link.

**Comment by sujato** [comment]
Well, that sounds fine, as long as it works. Don't strip hinting, though! 

For this application, as it is strictly an enhancement, going with all woff/woff2 has no downside, and could be a pilot for us.

**Comment by blake-sc** [comment]
I would think hinting is irrelevant to logo-sized text, likely there is no hinting data available for that px size. But in any case SVG wouldn't have any hinting data so a fair comparison would be without hinting.

**Comment by sujato** [comment]
Not sure I understand: are we talking about just the site logo, or the menu font? 'Cos if the latter, it's just ordinary sized fonts and hinting will matter. Having said which, if we are really building for the future, hinting is becoming much less important. Probably over half our users have screens that make hinting irrelevant already (any recent phone or tablet, and many modern PCs).

Incidentally, just a side comment on fonts, I have received from David B a beta version of Skolar Sans PE, which supports the full set of glyphs in 9 (!) weights. I'm using it for my local SC just to get a feel for it. It looks great in some contexts, but overall it's better suited as a text or display font, rather than a UI font as Source Sans is. Anyway, not in a rush to make any changes here.
