### ISSUE TITLE
sht fragment images + data on SC

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#140]
Rather than use Idb.bl.uk via the sht-lookup tool. 
See discussion on Discourse: https://discourse.suttacentral.net/t/idb-bl-uk-is-down/2466
Might not get copyright anyway.

**Comment by sujato** [comment]
To be honest, this is probably not worth it. Very few people can use these anyway, and despite the poor design of the idb site, they do have quite comprehensive metadata. So if we were to improve on what they do we would have to extract the metadata as well as the images. In addition, it is an ongoing project so, while it may be slow, extra information (such as transcription and translation of the fragments) can be added.

**Comment by ghost** [comment]
I agree there are more important things to do. So I will close this issue.
