### ISSUE TITLE
Clashing paragraph number

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#141]
On some texts pts paragraph numbers are shown overlapping.
FI https://suttacentral.net/en/pi-tv-kd1

**Comment by ghost** [comment]
@Sujato - The problem is that some of the paragraph number classes have negative top margins. I have taken this out with two of the pts classes and made them clear:both so the error does not appear any more. But I was wondering why these things have negative top margins (or even positive top margins) in the first place - it seems a bit messy and I would rather make all top margins on all paragraph classes 0 and make one general clear: both; on all of them.

**Comment by sujato** [comment]
Yes, and give them all a consistent left/right margin while you're at it.

The different margins were just a way to make them not clash, but obviously it was not a good design and should be replaced.

**Comment by ghost** [comment]
OK. Done that now. Just removed most margins and added clear:both;
Please have a look (on sc, not on staging).

**Comment by sujato** [comment]
That's great, much better, ta.
