### ISSUE TITLE
Expansion of Dhammapada coverage

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#148]
More complete coverage of gathas, especially Dhammapadas, has long been a desideratum. Finally due to Ayya Vimala's work we have the Patna and Gandhari Dhammapadas, as well as Anandajoti's concordance of the Indic texts. However there remains much to be done. This is a scratch pad of various resources.

Note the [A detailed comparative view of the Udanavarga by U Oslo](https://www2.hf.uio.no/polyglotta/index.php?page=fulltext&view=fulltext&vid=417&mid=0).

<table>
<tr><td><b>ID</b></td><td><b>Title</b></td><td><b>Stories?</b></td><td><b>Translation</b></td><td><b>Notes</b></td></tr>
<tr><td>dhp</td><td>Dhammapada</td><td>No</td><td>Buddharakkhita</td><td></td></tr>
<tr><td>pdhp</td><td>Patna Dhammapada</td><td>No</td><td>Cone</td><td>Rights to Cone's translation are presumably held by PTS.</td></tr>
<tr><td>gdhp</td><td>Gandhari Dhammapada</td><td>No</td><td>No</td><td><a href="https://books.google.com/books?id=aytJ5w074RYC">Brough is sometimes said to have translated this in his edition of the text</a>, but I don't think so. <a href="https://gandhari.org/a_manuscript.php?catid=CKM0077">Text is on gandhari.org</a>.</td></tr>
<tr><td>gdhp2?</td><td>New Version of Gandhari Dhammapada</td><td>No</td><td>?</td><td>A separate manuscript in Kharosthi of a text similar to the other Gandhari Dhp. Published as part of the EBMP by <a href="https://books.google.com.tw/books?id=ALZnXwZYlckC&dq=T.+Lenz,+A+New+Version+of+the+Gandhari+Dharmapada+and+a+Collection+of+Previous-Birth+Stories">Lenz & Glass in 2003</a>. Partial; about <a href="https://gandhari.org/a_manuscript.php?catid=CKM0018">60 verses</a> are on gandhari.org.</td></tr>
<tr><td>gdhp3?</td><td>Another New Version of Gandhari Dhammapada</td><td>No</td><td>?</td><td>A separate manuscript in Kharosthi. Published by <a href="https://gandhari.org/a_manuscript.php?catid=CKM0369">Falk in 2015</a>. Partial; about 70 verses.</td></tr>
<tr><td>uv</td><td>Udānavarga</td><td>No</td><td>Levi + Cakravati (fr), Webb (en)</td><td>The French translation <i>L’Udānavarga sanskrit</i> was by N.P. Chakravati in 1930 for the series Mission Pelliot en Asie centrale, Pub Paul Geuthner, Paris. This was chapters 1–21 except ch.4. Ch 4 was translated by Sylvain Levi in JA 1912. Chaps 1–15 of these French translations were translated into English by Sara Boin-Webb in the Buddhist Studies Review, beginning in 1981.</td></tr>
<tr><td>t210</td><td>Faju Jing</td><td>No</td><td>Dhammajoti</td><td>Translated by Weizhinan of Wu dynasty in 224CE. Very similar to the Pali. <a href="https://www.scribd.com/doc/51452894/Chinese-Version-of-the-Dhammapada">Translation by KL Dhammajoti</a> has 26 of 39 chapters, not sure if it has been completed. I am seeking permission for this.</td></tr>
<tr><td>t211</td><td>Faju Piyu Jing</td><td>Yes</td><td>Beal 1878, Willemen 1999</td><td>Translated by Faju and Fali of Jin dynasty, between 290 and 306 CE. It consists of selected texts from Fayu Jing with commentary. The <a href="https://archive.org/details/textsfrombuddhis00beal">partial translation by Samuel Beal</a> is public domain. A <a href="http://www.bdk.or.jp/english/bdk/list.html#list006">modern translation by Charles Willemen</a> is by Numata, but it has not yet been released online.</td></tr>
<tr><td>t212</td><td>Chuyao Jing</td><td>Yes</td><td>?</td><td>Translated by Zhu Fonian of Qin dynasty in 383CE. It is a translation of an old version of the Udānavarga together with a lost commentary by Dharmatrāta.</td></tr>
<tr><td>t213</td><td>Faju Yaosong Jing</td><td>No</td><td>Willemen, 1978</td><td>Translated by Tianxizai between 980 and 999 CE from the Udānavarga. Modern translation by Charles Willemen: The Chinese Udanavarga: A Collection of Important Odes of the Law (Fa chi yao sung ching). Mélanges chinois et bouddhiques 19. Bruxelles: Institut belge des hautes études chinoises, 19.</td></tr>
<tr><td></td><td>Ched Dubrjod Pa'i Tshoms</td><td>Yes</td><td>Rockhill 1883, Sparham 1983</td><td>Translated by Vidyāprabhākara around 9th century CE, from Udānavarga with Prajñāvarman’s commentary. Rockhill's translation is on U Oslo.</td></tr>
</table>

## Scope

So far we have about ten versions. This is of course not an exhaustive list. There will be many parallels in other texts. Further, there is a translation of the Tibetan into Mongolian. Dhammajoti refers to "two or three" Tibetan versions, but this seems to be a mistake. There is, however, a Tibetan commentary on the Udanavarga.

I have seen multiple sets of parallels for some of these, eg in Dhammajoti and Anandajoti, but these are are limited to certain texts. I don't think anyone has done a proper concordance for all verses. My guess is the most comprehensive would be in:

> 1. Dharmapada: a concordance to Udanavarga, Dhammapada, and the Chinese Dharmapada literature. Publications de l'Institut belge des hautes études bouddhiques. Série études et textes 3. Bruxelles: Institut belge des hautes études bouddhiques.

It would be a good idea to get this, if possible, although in point of fact it may not be necessary.

In addition, we have the resources by Ken Su:

 academia.edu (https://www.academia.edu/17535001/T210_and_Its_Core_26_Chapters_%E6%B3%95%E5%8F%A5%E5%BA%8F_%E8%88%87_%E6%B3%95%E5%8F%A5%E7%B6%93_%E9%87%8D%E8%AD%AF%E5%81%88%E9%A0%8C_2014_in_Chinese_).

http://yifertwtw.blogspot.tw/ 

My guess is we'll end up with 7000 or so parallels.

Creating a comprehensive list of these should not be too difficult, as we have most of the relevant data in digital form already. I would suggest the following method.
1. Establish the text IDs.
2. Extract the parallels from the U Oslo version; this does the Uv in Skt, Tib, and Chinese.
3. Match this with Anandajoti's tables, which correlates the Uv with the other Indic versions.
4. There remains some Chinese texts, which will probably have to be added by hand from Dhammajoti.

**Comment by ghost** [comment]
See discourse https://discourse.suttacentral.net/t/parallels-dhammapada/2822/3
I think only the Tibetan is still to do now.

**Comment by sujato** [comment]
closing this as virtually complete.
