### ISSUE TITLE
Class "supplied" is misused in English translations

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#150]
In the English translations by BB, for example MN 64, we find use of span class="supplied". This is incorrect. Supplied is meant for text-critical use, where an editor has reconstructed the original text. In translations, what is generally wanted in span class="add", which is text added for clarification. It would be a good idea to check through our translations and see how widespread this is.

**Comment by ghost** [comment]
In the English translations alone there are 5986 matches across 944 files.
In the Bahasa Indonesia texts there are 775 matches across 115 files.
In the Polish texts there are 115 matches across 10 files.

Shall I change these to class="add"? I'm a bit unsure if that is correct in all cases. For instance in https://suttacentral.net/pl/mn1 the class is added as some kind of way to highlight certain words. So maybe `<i>` would be more useful for this.

Of course in the Sanskrit/Gandari/Prakrit texts class="supplied" has the right function.

**Comment by ghost** [comment]
@sujato, can you let me know what to do with this?

**Comment by sujato** [comment]
Probably yes, change all these to add. I think it would be better to be clear about the definitions as I use them above. The only problem may be that add displays by default, which would be too intrusive. Perhaps add a language selector, so that add displays by default only on original language texts. 

`<i>` has a different meaning. It should be used specifically for quoting terms (usually Pali/Sanskrit) in another language; this is its meaning in HTML5 (or one of them, anyway). Italics for emphasis should be `<em>`.

**Comment by ghost** [comment]
That's done. All "supplied" has been changed to "add" in English, Polish and Indonesian translations and the "add" class only shows by default on pi, skt, lzh, bo, gr and pr. For the rest only when textual information is clicked.
I restarted the server but for some reason changes don't show up straight away so please check later.
