### ISSUE TITLE
Misuse of "speaker" class

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#151]
I just noticed that in Snp 2.7, the `<span class="speaker">` is used for verse 292. There's no "speaker" here. In the MS Pali text we have  (komāra) brahmacariyaṁ. Presumably the bracketed term was mistakenly changed. I've checked the files, and this mistake doesn't seem to occur elsewhere.

**Comment by ghost** [comment]
It reads:

`<p><a class="sc" id="sc292"></a><a id="p_18Sn_340" class="ms"></a>Aṭṭha­cattā­līsaṃ vassāni,<a class="brnum" id="br6"></a><br>`
`<span class="speaker">(komāra)</span><br>`
`Brahmacariyaṃ cariṃsu te;<br>`
`Vij­jācara­ṇa­pari­yeṭṭhiṃ,<br>`
`Acaruṃ brāhmaṇā pure.</p>`

So you just want the second line changed to:
`(komāra)<br>`?

**Comment by sujato** [comment]
no `<br>`, just (komāra) brahmacariyaṁ. It's an odd phrase, it appears to be hypermetrical and I suspect it crept in from the commentary, but that's what our text has, so we keep it.

**Comment by ghost** [comment]
I made the change locally and will upload it with the rest later today.

**Comment by sujato** [comment]
Done and done!
