### ISSUE TITLE
pts paragraph numbers

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#153]
I think PTS1 and PTS2 paragraph numbers show wrong in the Textual Information (see for instance sn1.1):
`<a class="pts1" id="pts11.1"></a>` shows up as `PTS(1st ed.) 11.1` but should this not be `PTS(1st ed.) 1.1`?

**Comment by sujato** [comment]
Ha ha, yes this is dumb. It needs a systematic fix. Probably we need to remark the texts something like pts1-1.1 and adjust the JS accordingly.

Also a minor point, there should be a space before the bracket.

**Comment by ghost** [comment]
Done.
