### ISSUE TITLE
additional parallels for avs,snp, and up

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#155]
Here are tables of extra parallels:

https://github.com/suttacentral/suttacentral/blob/master/parallels.zip

Notes:
- Avs should be ready to go, I made this. Mostly embedded parallels.
- Snp is a very thorough table made by a Japanese scholar. It's a scanned pdf, so it needs careful inputting by hand, then conversion to SC conventions. Perhaps we should get a volunteer to do this. 
- Up is a spreadsheet, it should be quite good, but probably not complete yet.

**Comment by ghost** [comment]
Just adding the reference to the Discourse discussion on Snp:
https://discourse.suttacentral.net/t/parallels-for-the-suttanipata-would-someone-like-to-volunteer-for-data-entry/2625

**Comment by ghost** [comment]
I've updated the parallels.zip file with the data for DHP parallels and updated Avs parallels.
Also added these to correspondence.csv but many with a # in front of it because these cannot be used until the new system is operational.

**Comment by ghost** [comment]
Asked @Qianxi on Discourse about the status of this project today.
