### ISSUE TITLE
Markup errors

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#156]
At SN 1.34 we have a couple of instances of the "speaker", to which the same class should be applied as in the Sutta Nipata. perhaps there are others!

Also, in the English translation of the same text, the verse of the second deva is mistakenly marked as prose.

**Comment by ghost** [comment]
I changed this one. But as you continue translating, this issue and the one about SC numbers not being per paragraph, will automatically be resolved. 
I have a little python program that puts SC numbers on every paragraph of a text if need be.

**Comment by sujato** [comment]
Which issues exactly will be solved? The "speaker" class?

The numbering? Okay, good to know. But we need to make sure that the cross-references still link up.

**Comment by ghost** [comment]
Speaker class and the blockquote for the other deva has been changed in the English version. But no doubt things like that will keep on popping up.

I will make a python program to detect how often the SC numbering in the Pali versions don't start with "1" and then take it from there. I'm putting this on a new issue.
