### ISSUE TITLE
soft hyphens bugger up some CSS rules

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#158]
We've added soft hyphens to long words in the Pali files. In the class="vagguddanagatha" these have been added, and result in the appropriate CCS not being applied. See eg SN 22.159.

We should remove soft hyphens from this class, and check that this bug doesn't affect any other classes.

**Comment by ghost** [comment]
I have changed this for vagguddanagatha. As far as I can see, the only other class that could be affected is uddanagatha but I checked this and there do not seem to be any with soft hyphens in that.
