### ISSUE TITLE
search bug in non-standard languages

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#163]
When I search for a Chinese term, setting it to use Chinese, and I hit the "next page" button, it gets confused and doesn't deliver the page properly. I think the "next page" and "set language" and getting confused. Try search this: 計

It works fine if you edite the URL by hand, eg: https://suttacentral.net/search?query=%E8%A8%88&lang=lzh&offset=10&limit=10

**Comment by ghost** [comment]
This is issue https://github.com/suttacentral/suttacentral/issues/134
