### ISSUE TITLE
Capitalize headings

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#164]
When preparing the various texts I have in some cases left the heading uncapitalized. This was for various reasons, often because the source texts in Sanskrit were like that. At the time these were served with small caps so it was no big deal. However with the Noto fonts it becomes quite noticeable. We can deal with this using CSS capitalize, which is fine as an interim. But really our texts should be consistent in such a basic element.

So we should go through and ensure that all headings in all texts are capitalized. Note this includes <p> within .hgroup. 

It will mostly be an issue in lzh and skt texts, I think.

**Comment by ghost** [comment]
Do you want capitalized (first letter only), small caps or uppercase? And do you have an example of where this occurs?

**Comment by sujato** [comment]
here's one example: https://suttacentral.net/skt/divy1

another: https://suttacentral.net/lzh/lzh-dg-bu-pm-2#ss1

You'd need to use a regex to sniff out other cases.

They should be capitalized the same as the majority of texts. (As a principle, one should never use all uppercase when writing titles, as it is trivial to make all uppercase in CSS. Capitalizing is not trivial, however, as in English anyway, not every word is capitalized. Small caps is always display only, and is handled in CSS. Technically there's no such thing as separate small caps characters, they are just display variants.)

**Comment by ghost** [comment]
Done as css for language skt. All others I changed by hand because there were only a few. I did this so as not to change the part-capitalization of English and other language headers, where not every word is capitalized.
However, I'm not entirely happy with this solution: it's a bit of a patch. Maybe at some point we have to re-do the headings.scss file.
