### ISSUE TITLE
Menu display bug for Prakrit

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#166]
I just noticed in the main SC header menu, under Sutta>Prakrit, there's a couple of blank `<li>` added under the actual menu items, these highlight on hover. They should be removed.

**Comment by ghost** [comment]
This is the "improvisation" I talked about when I added it. The reason is that without the blanks, the menu looks a complete mess. At least now it is nicely aligned. The only other thing I could suggest is to swap Prakrit and Tibetan around in the menu.

**Comment by sujato** [comment]
Okay, fine, but it's still a bug and should be fixed. @blake, when you get a chance …

**Comment by blake-sc** [comment]
Fixed by adding visibility: hidden;

**Comment by sujato** [comment]
Sorry Blake, I'm reopening it, this is a very hacky solution: put the code in and then hide it. Most inelegant! Sure, it's not a big priority, but still, we can do better.

**Comment by ghost** [comment]
The problem will be solved as soon as I put more Gandari Dhp texts on the site and into the menu (and swap Prakrit and Gandari). Of course the underlying cause of the problem will not be solved that way.

**Comment by blake-sc** [comment]
Using visibility: hidden; is imo a decent solution when you want an element to only consume space. But it can also be solved by using `#panel .language {min-height: 9.5em}`
