### ISSUE TITLE
Romanian translation to add

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#170]
Contact http://dhamma.ro/

**Comment by ghost** [comment]
I've prepared the files but am waiting for permission and some information from the people behind the website.

**Comment by ghost** [comment]
I've emailed them twice now, once via their webform and once by email direct but no joy.
As most of the texts (apart from 2) are direct translations of Tanissaro and they have the same copyright notice on them as AccessToInsight, would it be OK for me to just go ahead and publish them? I just don't know who the translator is.

**Comment by sujato** [comment]
Yes, go ahead, if they have licence similar to Thanissaro's this is fine.

**Comment by ghost** [comment]
Done
