### ISSUE TITLE
Navigation fixes

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#172]
I'm moving this issue here from Discourse.

As we are working on an improved backend data structure, I wanted to make a list in one place of specific issues with the navigation that we can fix at this time. In no particular order.
1. In /ps, ps 2.7.1 appears as a parallel of the Dhammacakka, it is out of place in hierarchy here.
2. In /kd, the first three entries likewise appear out of place.
3. In the Tibetan texts, we should remove the "critical edition" category, and scratch peking. Main ref system should be Derge, peking and critical editions can be vol/page.
4. In Sanskrit Suttas, we inconsistently use "Other Fragments" in menu, and "Sanskrit Fragments" in ID. Neither is useful or accurate, as many of these texts are quite large and complete. I would suggest "Sanskrit Miscellaneous". And it should be at the top of the menu, as it is by far the most important section of the Sanskrit texts.
5. In the Anguttara Ones there are a number of ranges, the numbering needs to be adjusted, see https://discourse.suttacentral.net/t/sutta-entitle-and-numbering-in-an/3433
6. The Pali Parivara. This is conceptually broken, with the "Parivara", the in brackets "Bhikkhu Parivara" and "Bhikkhuni Parivara". The "Parivara" links to the Pali text with Vol/Page refs, while the other two pages link to the parallels for the patimokkha rules. Obviously these should be combined, so that we have one navigation entry for the Parivara. There is no one place for the various patimokkha rules in the Parivara; it treats them all multiple times. The point of including them is simply to be able to see the parallels from the main texts, so there's no need to have a separate page listing these rules, it just clutters up the navigation. I would suggest we simply remove the "Bhikkhu Parivara" and "Bhikkhuni Parvara" from the main navigation. Note that the comparable menu entry under Mahasanghika Khandhaka is in fact correct; this is because the parallels are organized in terms of Khandhakas, but these are not actually found in the Mahasanghika Vinaya.
7. Pali Khandhaka. The division page currently begins with three texts as parallels, before the Mahakkhandhaka (which is the actual beginning of the division); these are a legacy from an older way of treating this. These parallels should be removed from the division page, and should instead show up as partial parallels on the details pages of the appropriate chapters of the Khandhaka.

**Comment by sujato** [comment]
see parallels for mn36, we have two entries for Lal, but these are not properly linked.

**Comment by ghost** [comment]
The problem is that it refers to something called lal17a, which does not really exist as a text but is a combination of lal17 and lal22. This error is also replicated in the new parallels.json file.
I have changed this now on the SC life version into Lal17 and Lal22 separate, but that is only a makeshift solution.
So when Blake changes over to the new parallels.json file, it needs to be looked at for a more permanent solution.

**Comment by aminah-sc** [comment]
All changed on the new site.
