### ISSUE TITLE
Chinese lookup bug

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#175]
When the Chinese lookup displays a term, you can click on the headword and go to the DDB main site for a detailed view. However this is broken in the case of terms that are surrounded with a red dot border.

**Comment by ghost** [comment]
Can you give an example of this?

**Comment by sujato** [comment]
Sure, see SA1, the character 為

**Comment by ghost** [comment]
For as far as I can see, this particular character does not exist in the DDB. When doing a more extensive search, it tells me that this character is a Japanese form and equates this character with another character: 爲, which does exist in DDB, and is the modern Chinese simplified version of it.
One thing I might be able to do is to have characters that are not directly in the DDB redirect to another URL than the normal one, namely: http://www.buddhism-dict.net/cgi-bin/dealt-lookup?q=%E7%82%BA

Another thing I noticed is that if you click on any character, it directs you to the DDB (not in a new tab either) but it asks for a username and password without any further instructions. Most people will not know that you simply have to type "guest" in username and then you will be able to get through. Is this something to mention in the instructions in our sidebar when somebody activates this function?

**Comment by sujato** [comment]
Okay, well I think we need @blake-sc's input here, it is a designed feature, probably for the reasons you state. We did discuss it at some point, but I can't remember. Maybe there is nothing to be done about it after all.

I didn't realize about the lack of notification for the DDB main entry; it would indeed be good to implement something. Rather than put it in the sidebar, i'd suggest inserting it as a "title" attribute on the headword in the lookup bubble. I can't get my inspector to reveal the correct code, but something like:

```
<span title="Go to full entry at the DDB. Login with user name "guest"">雜</span>  zá: to mix
```

**Comment by ghost** [comment]
Oops. I'm a bit too quick again. Just done it ... it now redirects to the other URL which mentions the modern equivalent (and you can click on the modern equivalent to get the meaning). Have a look. I can undo it if needed. 
Personally, I would also like to have this kind of redirect in a new tab ... (target="_blank")

I feel that putting a notice in the lookup bubble would be much too big there. But I've done it so you can see what it looks like. BTW, this is not something you have to do each time, only the first time when you login. After that, it remembers that for the session.

PS. Just noticed that the entries in the red dotted lines don't go to the DDB but to CJKV. Makes no difference for the login, but best to change the text in the popup for the lookup bubble.

**Comment by sujato** [comment]
Wow, that was fast. Works great. I don't think the size is a problem, the main thing is to be clear. 

And yes, target="_blank" would be better; (I use middle click, so I don't notice.)

**Comment by ghost** [comment]
Ok. Target done and also the mention of CJKV instead of DDB for the entries that DDB doesn't have. 
Just a bit of fun ... pretty easy really.
