### ISSUE TITLE
Myanmar font bug

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#176]
User myint myat alerted us to a bug in the Myanmar font. I have confirmed it on my nexus. In fact we are not delivering the Noto font at all in Myanmar, it just shows up as boxes on my Nexus. The other complex-script fonts look fine.

**Comment by blake-sc** [comment]
Confirmed: The entries for Noto Sans Myanmar were missing. I've added them. It seems to be working fine now.
