### ISSUE TITLE
In firefox discourse shows a "seam" at the join of "SuttaCentral" and "Discuss and discover" 

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#179]
That is, in the site header. Screenshot attached. It looks like box-shadow is escaping, perhaps a z-index needs fixing.

![screenshot from 2016-08-07 15-34-22](https://cloud.githubusercontent.com/assets/6112010/17461156/87cbefc8-5cb4-11e6-93b7-06736bf103d2.png)

**Comment by sujato** [comment]
Bump! This is still present, i can see the seam in the recent screenshot from Linda 

https://discourse.suttacentral.net/t/new-discourse-home-page-design/3502/11?u=sujato

**Comment by ghost** [comment]
Sometimes I just hope things will disappear by itself if I ignore them long enough. Guess not.
Anyway, it's done. Check Fireforx.

**Comment by sujato** [comment]
Great, thanks.
