### ISSUE TITLE
<p> tags get misplaced in cooking of dictionary entries with map

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#183]
Okay, so this is a nicely obscure one. Check out https://suttacentral.net/define/nigrodh%C4%81r%C4%81ma 

Notice that before "Among others mentioned" there's a new line but no space; i.e. there is no proper paragraph. On Github the paragraph is there:

```
<span class="ref">SN.iii.91<em>f.</em></span></p><p>Among others mentioned
```

However in the "view page source" for the site the `</p>` has disappeared:

```
<span class="ref">SN.iii.91<em>f.</em></span><p>Among others mentioned
```

It has in fact been moved to the beginning of the entry, where we find:

```
<dd>
<p></p><div class="google-maps">
```

Whereas the Github file has:

```
<dd>
<p><div class="google-maps">
```

**Comment by ghost** [comment]
I can fix this but need to be sure that you are not working on it.

**Comment by sujato** [comment]
I am working on it. But would this make a difference? The problem is that the file is being changed somehow between the file on the server and that in the browser.

But anyway, give me a day or so and I'll send you the revised file.

**Comment by ghost** [comment]
This issue is fixed.
