### ISSUE TITLE
Reconcile ref classes for DN and translations

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#186]
In DN, unusually, there is a widely adopted system of chapter/section, first used in the PTS editions. However in the English translation this is labelled "WP", which is incorrect, as Wisdom Publications merely adopted it. We should ensure that the DN translations use the proper naming conventions.
- SC = remains
- PTS = either PTS vp en or PTS vp pi, this needs to be checked and fixed
- WP = PTS cs

We should also check other translations to ensure they follow these, too.

**Comment by ghost** [comment]
???? I did a full check of the classes mentioned in the English DN and I cannot find what you are saying.
There are the following classes:
- BPS (in Bhikkhu Bodhi's translations)
- pts-cs
- pts-vp-pi
- pts-vp-en
- pts
- pts-p-pi
- sc

**Comment by sujato** [comment]
This is embarassing, I don't know where I went wrong, sorry about that.
