### ISSUE TITLE
Make text size properly responsive in mobile view

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#187]
I don't quite understand this, but if i zoom the page on a desktop view, the text size changes as expected, and adapts to the container size; Ii.e. no matter how big I make it, it always fits (at larger sizes it switches to the mobile view). However, if on a mobile view, when I zoom, the whole container just gets bigger and disappears off the screen. This means effectively that mobile users are stuck with the default font size. Which is fine, unless you don't like that.

The mobile version should be scalable just as the regular version.

I don't know how to emulate this glitch on a regular screen; in the mobile emulator on Chrome, zoom doesn't work. But using a touchscreen and iPhone 6 emulator, here is the default view:

![screenshot from 2016-10-05 18-07-45](https://cloud.githubusercontent.com/assets/6112010/19109238/066fbd00-8b27-11e6-9037-87f38a117ac2.png)

And here is a zoomed view, with the text clipped on either side.

![screenshot from 2016-10-05 18-08-05](https://cloud.githubusercontent.com/assets/6112010/19109257/18d0fdc4-8b27-11e6-85fc-bd3ea2061e64.png)

**Comment by blake-sc** [comment]
Do you mean that it zooms in but without being scrollable?

**Comment by sujato** [comment]
No, it scrolls fine. like in the screenshot above, the problem is that when you zoom in the text doesn't reflow, it disappears off the sides of the device; i.e. the whole text container gets bigger, not constrained by the viewport size. Like I said, I haven't been able to emulate this on an ordinary screen, it seems to be purely a touchscreen issue.

But i just checked a bunch of well-designed responsive sites, and all of them do the same thing. So it looks like there may be nothing to be done.

In fact it is a recognized issue discussed in a number of forums. And it is implemented very differently in browsers: Firefox doesn't current have pinch-to-zoom at all.  It seems the behavior of scale-zoom—which apparently is the correct term—is regarded as preferable to reflowing since it doesn't result in the page rearanging itself to the mobile view (?)

https://www.reddit.com/r/firefox/comments/1mkqry/firefox_24_released/cca7taf 
https://bugzilla.mozilla.org/show_bug.cgi?id=789906
http://www.iheni.com/mobile-accessibility-tip-dont-suppress-pinch-zoom/
https://bugs.chromium.org/p/chromium/issues/detail?id=136329

It all seems very odd to me, how come something so basic doesn't work?

Anyway, what to do? Given that our font size is the device default, perhaps that could be increased on mobile? But that might not suit most people. Maybe we go back to the bad old days and put a "font size" button in the sidebar? Or maybe get users to use the non-pinch zooming?
