### ISSUE TITLE
Stop or limit Safari Reader from joining multiple pages into a single article

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#188]
See this thread: 

https://discourse.suttacentral.net/t/safari-reader-view-on-ios-devices-loads-infinite-pages/3341/2

Question asked here:

http://apple.stackexchange.com/questions/255913/how-do-i-stop-or-limit-safari-reader-from-joining-multiple-pages-into-a-single-a

**Comment by ghost** [comment]
Check if this is really still valid for the new site.

**Comment by ghost** [comment]
A Polymer site does not work with Reader at all, not on Safari and not on Firefox. This is because it is not a plain html site. So this is a non-issue and can be closed.
