### ISSUE TITLE
Populate vol/page info for mahavastu

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#192]
Currently the vol/page info for Mahavastu is unhelpful, it just gives the vol. The page info is in the text files, we should extract it and apply.

https://suttacentral.net/skt-lo-mvu

**Comment by ghost** [comment]
I don't get it. The source text files here: http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/4_rellit/buddh/mhvastuu.htm show exactly the same numbers as our texts:

Mvu_1.1 = Sen 1.1
...
Mvu_3.463 = Sen 3.463 (https://suttacentral.net/skt/skt-lo-mvu111#sen3.463)

**Comment by sujato** [comment]
sorry, i should have been clearer. I meant the vol/page info on the division table page, i.e. https://suttacentral.net/skt-lo-mvu

**Comment by ghost** [comment]
Done ... please have a look.

**Comment by sujato** [comment]
very cool, may I ask how you did it?

**Comment by ghost** [comment]
20 minutes of intensive manual labour. :-)
Just added the numbers by hand in vinaya_rules.csv. Please note I used an n-dash!

**Comment by sujato** [comment]
Oh, I noticed the en-dash, don't worry!
