### ISSUE TITLE
Problem with inheritance of hanging punctuation in inline-block elements

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#193]
Check out https://suttacentral.net/define/viseni 

You'll notice that the "ref" entries exceed their bounds. This is because the paragraph starts with a “, and our quotehanger applies text-indent to it. This is fine, but apparently the ref inherits this, creating the problem. The reason this appears is because I recently redefined the ref class as inline-block. The reason for doing this, in turn, is because in such elements the vertical padding in inline elements is quirky (which in turn is because of line heights and different fonts, yada yada) Anyway, I found that the vertical padding sat much more naturally with inline-block. So what to do? Get rid of inline-block and add padding, or change the way text-indent is handled?

**Comment by blake-sc** [comment]
Looks like this can be fixed in general with the rule:

```
p > * {
text-indent: initial;
}
```

Then the paragraph is indented but the property isn't inappropriately inherited by any children. It seems to work fine but I wonder if there would be any unforeseen consequences to this?

**Comment by sujato** [comment]
Yeah, not sure. Most of the hanging quotes solutions I see use a negative margin on the quotes, which avoids this problem, but text-indent would seem to be the more semantic approach. But your suggestion should work, I can't see why you'd want nested elements with text-indent.
