### ISSUE TITLE
Review filtering of dictionary results in search

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#196]
Check the results for this:

https://suttacentral.net/search?query=ujjha*&lang=&define= 

Under Ujjhatti it says "feminine irritation, discontent". Which sounds kinda sexist. But *feminine* is just the grammatical case!

On the same page, we find that most of the entries are weirdly formed. Few if any give the initial, basic meaning, instead they start somewhere in the middle of the entry. 

Sometimes this because the searched term is not the head word. In such cases it would be better to give the search result as the head word, the initial definition, an ellipsis, then the context of the searched word.

In other cases the searched term is in fact included in the headword, but still we don't get the main entry. 

I would suggest that whenever we get a search result from a dictionary, we should filter out grammatical and etymological information (which is now reliably marked up). We should in each case give the headword and the initial definition, and further context if the searched-for term only occurs later in the entry.

**Comment by blake-sc** [comment]
Hmmm, yes. That is a result of removing the markup at search indexing time, it is hard to both have markup in searchable content and have it not mess up with displaying snippets and highlighting. The solution would therefore be to strip the grammar information out of the definition before indexing, the grammar information could be indexed separately.

**Comment by sujato** [comment]
Do we need to index it separately? Why not just strip it; I can't think why you'd want to use that for search. The etymology, on the other hand, should stay, but that's at the end of the entry so not such a problem.

**Comment by ghost** [comment]
This is no longer valid on the new site where markup is very different and dictionary is in json files. There might be other issues but I suggest making a new issue for those when we come across them.
