### ISSUE TITLE
Resizing of subdivision pages not showing language options

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#198]
https://discourse.suttacentral.net/t/khandaka-corrections/3621/22?u=vimala

The problem seems to appear only on pages with long titles and especially in Firefox but also other browsers like Chrome and IE.

**Comment by sujato** [comment]
If I understand the problem correctly, the translations column is still present, but is scrolled off the side of the page. Is that right?

I think this is a marginal problem. Given that we hope to roll out an entirely new implementation soon, which may well involve a redesign of these pages, I would suggest we wait until then and see if the problem still occurs.
