### ISSUE TITLE
Swath preprocessor for Thai, and possibly other preprocessors

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#207]
As per this Discourse thread, we should use Swath to preprocess all Thai text. If we find other preprocessors for other languages/scripts they can be applied similarly.

https://discourse.suttacentral.net/t/smart-word-analysis-for-thai/5833/3

**Comment by aminah-sc** [comment]
Issue moved to [suttacentral/suttacentral #1103](https://github.com/suttacentral/suttacentral/issues/1103) via [**ZenHub**](https://www.zenhub.com/)
