### ISSUE TITLE
Yogacarabhumi, incl. Sarirathagatha with parallels

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#208]
Our attention was drawn to the Sanskrit text of Asanga's Sarirarthagatha, which consists entirely of verses with parallels in the EBTs. Source:

http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/6_sastra/3_phil/buddh/asycsaru.htm 

This is a section of his Yogacarabhumi. Another part of this, the Sravakabhumi, is also on GRETIL:

http://gretil.sub.uni-goettingen.de/gretil/1_sanskr/4_rellit/buddh/srabhusu.htm

Let us create a new folder in html_text/san/su called `ybs`. There we can add the Sarirarthagatha and in future the Sravakabhumi.

We need to create the following abbreviations:

- ybs = YBS = Yogācārabhūmi
- sag = SAG = Śarīrārthagāthā
- sbh = SBh = Śrāvakabhūmi

## Parallels:

- The Uv parallels are identified already in the GRETIL source.
- Several sections are named.
- I have identified almost all the remainder in the Sagathavagga.
- I have not attempted to identify all parallels, just identifying one, usually full, parallel.
- One passage is in prose and is a partial parallel of SN 1.1. Oddly, it is titled *geya*.

## Files
- `sag.html`: HTML file, ready to go.
- `sag_parallels.csv`: parallels in CSV.

[sag.zip](https://github.com/suttacentral/suttacentral/files/1364536/sag.zip)

## 2-do

- Add the HTML file to `/san/su/ybs`
- Integrate the parallels in `sag.csv` in `parallels.json`
- Ensure that the text reference metadata IDs `sag` and `sbh` are properly registered: I am not sure how this works on the new site.
- We can go ahead under the assumption that the Sravakabhumi will be added. Preparing the text is straightforward; finding parallels, not so much. But the text contains large amounts of direct quotes from the early texts, and Sanskrit variants are always useful.

**Comment by ghost** [comment]
Just to keep a record here, I've done the following:
1. Add the html file
2. Integrate the parallels in the parallels.json
3. Created a file called ybs.json in structure/division
4. Added the following to structure/sutta.json:
```
  {
    "name": "Śarīrārthagāthā",
    "uid": "sag",
    "subdivision_uid": "ybs",
    "vagga_number": "",
    "number_in_vagga": "",
    "language": "san",
    "acronym": "SAG",
    "volpage": "",
    "biblio_uid": ""
  },
  {
    "name": "Śrāvakabhūmi",
    "uid": "sbh",
    "subdivision_uid": "ybs",
    "vagga_number": "",
    "number_in_vagga": "",
    "language": "san",
    "acronym": "SBh",
    "volpage": "",
    "biblio_uid": ""
  },
```
5. Added `ybs` to structure/pitaka.json and structure/language.json
6. I did not add anything to structure/menu-structure.json because I noticed some items missing there like "uv". So not sure where this belongs.
7. created and uploaded sbh.html.
8. Registered all paragraph numbers for both sag & sbh.

**Comment by ghost** [comment]
Still to do: 
Check where these are registered and where in the menu they should be.

@sujato: is there any volpage or biblio info that you want to put in these above?

**Comment by sujato** [comment]
No, just what's in the original file.
