### ISSUE TITLE
More complete set of Russian translations

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#209]
As per conversation here: https://discourse.suttacentral.net/t/russian-translation-of-the-entire-majjhima-nikaya/6735/5 (PM to sujato)

Here are the complete translations by SV in Russian, including the entire MN, and much else. These were supplied by Vstakan, who has the agreement of the translator to publish.

[Russian_Translations_by_SV.zip](https://github.com/suttacentral/suttacentral/files/1384362/Russian_Translations_by_SV.zip)

We should prepare and add these in due course, but wait until after the new site is ready. I'm keeping them here so as not to lose them!

**Comment by ghost** [comment]
MN sent to Penny to do.

**Comment by SamaneriVimala** [comment]
Remind me how to do this again with Sublime so the Cyrillic characters show up ...? Then I will send it off to Penny (at least the MN and we can see about the rest later).

**Comment by ghost** [comment]
Aminah has started coding the rest.

**Comment by ghost** [comment]
I think they are all done now.
