### ISSUE TITLE
Beal’s English translation of Chinese Dharmapada

### ISSUE THREAD

**Issue by aminah-sc** [suttacentral/legacy-suttacentral#217]
#### Task:

Add Samuel Beal's 1878 English translation of Chinese Dharmapada (T211) to SuttaCentral.

#### Definition of done:

- [ ] Text preparation (clean-up & coding)
- [ ] Uploaded

#### Additional detail:

* Get the text [here](https://archive.org/details/textsfrombuddhis00beal) (text file available).  
* See [this D&D thread](https://discourse.suttacentral.net/t/chinese-tibetan-dharmapadas/8545) for more on adding Chinese/Tibetan Dharmapadas to SuttaCentral.

**Comment by ghost** [comment]
I've revamped the text file a bit but it needs a bit more work because verses are in between the text and OCR is not very good so the whole thing will have to be read through and compared to T211:

https://discourse.suttacentral.net/t/chinese-tibetan-dharmapadas/8545/22?u=vimala

**Comment by ghost** [comment]
Yosoj is working on the OCR after which I will code it.
