### ISSUE TITLE
Rockhill’s English translation of the Tibetan Udānavarga

### ISSUE THREAD

**Issue by aminah-sc** [suttacentral/legacy-suttacentral#218]
#### Task:

Add W. Woodville Rockhill's 1883 English translation of the Tibetan Udānavarga ("Northern Buddhist version of Dhammapada") to SuttaCentral.

#### Definition of done:

- [x] Text preparation (clean-up & coding)
- [x] Uploaded
- [x] Add to menu

#### Additional detail:

* Get the text [here](https://archive.org/details/udnavargacolle00bkah) (text file available).  
* See [this D&D thread](https://discourse.suttacentral.net/t/chinese-tibetan-dharmapadas/8545) for more on adding Chinese/Tibetan Dharmapadas to SuttaCentral.

**Comment by ghost** [comment]
I cleaned the file a bit here: 
https://discourse.suttacentral.net/t/chinese-tibetan-dharmapadas/8545/22?u=vimala

But it needs some work and reading through the whole thing because the OCR is not very good.

**Comment by ghost** [comment]
Yasoj from Discourse is going over the OCR to clean it and someone can do the coding afterwards.

**Comment by ghost** [comment]
Uploaded but new bug: Paragraph labels are not visible. New issue created:
https://github.com/suttacentral/suttacentral/issues/925

Both English and Tibetan are done.

**Comment by ghost** [comment]
Bug was a non-bug and resolved itself with emptying the cache.

**Comment by ghost** [comment]
Dear Ayyā, 

Good that it is sorted out. I will just mention that one of our Professors here is Geshe Lozang Jamspal who has recently translated the Tibetan Udānavarga for the 84,000 project. As far as I can see it is not published yet, but it should be soon. I know he was checking it against the Sanskrit, so it may provide a better source as soon as it is up. 

Metta, Anandajoti

**Comment by sujato** [comment]
All looks good.
