### ISSUE TITLE
Don't reduplicate suttaplexes 

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#220]
Currently the suttaplexes have to be downloaded separately for each level of hierarchy, vagga, pannasa, etc. This increases data usage and is generally not a good idea. 

To fix this we should enable slicing, basically putting in little entries signifying the end of a vagga/whatever, allowing slicing up the division level.

**Comment by aminah-sc** [comment]
Issue moved to [suttacentral/suttacentral #1102](https://github.com/suttacentral/suttacentral/issues/1102) via [**ZenHub**](https://www.zenhub.com/)
