### ISSUE TITLE
Check numbering PTS images (Segmented texts)

### ISSUE THREAD

**Issue by aminah-sc** [suttacentral/legacy-suttacentral#221]
When segmented texts are uploaded, check the text-images and if they display correctly.

**Comment by ghost** [comment]
@Aminah-SC Aminah .. can you refresh my memory, what was this about again? The text-images seem to work OK as far as I can see but we need to have PTS2 images but that would be a different issue.

**Comment by aminah-sc** [comment]
Thanks, Ayya @SamaneriVimala. I'm afraid I don't have more info that what's given here - this is an import of one of two Jira tickets you sent for me to add here by email (on 22/02/18). The second issue (#222) has a lot more info. The above is all I had to go on for this one, but I wanted to make sure it was logged rather than lost (maybe it can be merged, or closed?). 

In the mentioned email you wrote:

This has to do with the text images.
For instance, if you go to https://next.suttacentral.net/dn3/en/tw_rhysdavids and put Textual Information on, you see something like this:

![image](https://user-images.githubusercontent.com/36522678/37683518-c40b1102-2c84-11e8-9034-d1e5f48c73dc.png)

And that little book you should be able to click on and you get a text image (does not work right on that version of Next yet) so then you know what these two tickets are on about.

BTW, I guess you already know, the little book icon doesn't show in Firefox.

**Comment by ghost** [comment]
I will make a new issue to add point 3 from issue 222 and close this one.
