### ISSUE TITLE
Add Indonesian Translation of Patna Dhammapada

### ISSUE THREAD

**Issue by aminah-sc** [suttacentral/legacy-suttacentral#223]
#### Task:

[Arya Karniawan's Indonesian translation of Patna Dhammapada](https://github.com/suttacentral/legacy-suttacentral/files/1823397/Patna-Dhammapada_Karniawan_Indonesian_corrected_01.docx) was given (by the translator by email) for publication on the SuttaCentral website. The text needs to be extracted from the linked .docx file and coded for SC. 

#### Additional detail:
Arya's translation was made from [Ven. Anandajoti English translation](https://www.ancient-buddhist-texts.net/Texts-and-Translations/Patna-Dhammapada/Patna-Dhammapada.pdf).

**Comment by ghost** [comment]
Penny is starting with the English translation.

**Comment by ghost** [comment]
English translation uploaded.

**Comment by ghost** [comment]
Indonesian translation uploaded too.
