### ISSUE TITLE
Font ligatures

### ISSUE THREAD

**Issue by jingoro** [suttacentral/legacy-suttacentral#54]
We would like to make sure font ligatures on SuttaCentral. Recent commit f47ae900d9 did the preliminary work.

**Comment by jingoro** [comment]
There are still a minor issue with the "fj" italic ligature which makes its appearance on Windows/Firefox and Windows/Chrome. See the image below.

![screen shot 2013-12-04 at 2 51 00 pm](https://f.cloud.github.com/assets/21310/1678358/a621ca86-5d36-11e3-8587-a42f1d9465eb.png)

The fonts test page is visible at http://suttacentral.net/fonts.

Linux/Firefox, OS X/Firefox, OS X/Chrome and OS X/Safari all seem to be working fine.

**Comment by sujato** [comment]
I've tested it with Ubuntu/Chromium 30 and Ubuntu/Firefox 25: in both cases it works well.

"fj" will obviously be a rare combination in English, but it will appear in some european langages. (I don't know whether the suttas talk about "fjords"!)

We have no bold/italic font, so what we see there is a faux-bold from the italic. Best to omit this as it is (by choice) not part of our design. (Bold italic is a rarely-used face, and including it adds an unnecessary hit to our downloads.)

Also, ligatures are not part of the small-caps, so this test is unnecessary. 

Nevertheless, it is probably not a bad thing to keep a page like this for testing the fonts more generally. We could extend it to include the coverage of Vietnamese glyphs, the sans fonts and so on. In addition, perhaps we could add the Chinese, Korean and other scripts that we use, so we can have a one-stop place for certifying all our fonts. (Note that for Chinese there is no bold or italic).

**Comment by jingoro** [comment]
@sujato I made some changes in 01df373c05 to give some additional samples, including those for Vietnamese and Chinese. You can see the results on the [fonts test page](http://suttacentral.net/fonts).

**Comment by jingoro** [comment]
@sujato Additional changes were made in cee69efa85 based on your last email. This looks like it fixed the above glyph problem as well as adding better support for Vietnamese characters.

**Comment by sujato** [comment]
Excellent, everything appears to work well now, although I haven't tested it across browsers.

**Comment by jingoro** [comment]
@sujato I tested the fonts on OS X Chrome/Firefox/Safari, Windows Firefox/Chrome/IE10, Linux Firefox. I think this is good test coverage.
