### ISSUE TITLE
Better 404 page

### ISSUE THREAD

**Issue by jingoro** [suttacentral/legacy-suttacentral#58]
It would be great if the 404 page were improved. A few ideas:
- Use the search functionality to help the user find what they were looking for. For example, if the URL was /dn231/en, it would consult the search engine for `dn231 en`, then `dn231`, then `dn23`, then `dn2` then `dn`, etc.. If any results come up, it would display that to the user.
- Style the page using the standard SuttaCentral template.

**Comment by sujato** [comment]
done.
