### ISSUE TITLE
Natural Language Processing (NLP)

### ISSUE THREAD

**Issue by jingoro** [suttacentral/legacy-suttacentral#62]
From @sugato:

> I'd like to introduce NLP analysis for texts (probably using the Python
> NLTK). This could be implemented in various ways, but here is a simple
> suggestion for an initial rollout.
> 
> We have a button that says "Analyze text", next to the "textual Information"
> button. Hit it: things crunch, and a bunch of figures pop out. This
> could include things like:
> - word count
> - average length of words
> - longest words
> - most frequent words
> - most frequent words used in proximity with each other proportion of
>   grammatical forms (for this we would need at least a basic Pali parser,
>   which hopefully Nandiya will build one day....)
> - metrical analysis of verse
> 
> That's a start. Some of these things will require more detailed knowledge of
> Pali, but most are just basic NLP tasks. i'd like to evolve over time to more
> sophisticated functions; we could define a range of texts; compare statistics
> on various texts or ranges; provide an interface for customizing queries;
> identify parallel passages across languages by analyzing syntax and
> vocabulary, and so on.

**Comment by sujato** [comment]
discussed elsewhere
