### ISSUE TITLE
Burmese translation text corrections

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#72]
As per Nay's email of 1/3/2014, there are some errors in Burmese translations.

The texts are available here:

https://drive.google.com/file/d/0B2akdbV6bsaaNFlXbnJrOWxKNVpUZ1AzRm1HZ0hnLUVzRXdz/edit?usp=sharing
https://drive.google.com/file/d/0B2akdbV6bsaaZ2ZCVlUwbHExRUtsbWROM3Q2SlZuWTlXOEhV/edit?usp=sharing
https://drive.google.com/file/d/0B2akdbV6bsaaaU9RQ3pqT0ZTamwwMDI2ZFBPdGhLVEo3MHFB/edit?usp=sharing

**Comment by ghost** [comment]
I can pick this up.  Is Nay happy to help me with this and if so, can you send me her email address?

**Comment by sujato** [comment]
It's his, and sure, I will send the email. 

Another outstanding task is completing the Vietnamese texts, I am assembling them and it would be great if you could look at these.

**Comment by ghost** [comment]
I've written Nathan and uploaded the drive files to SC - I figured with the help of google translator that that was all that was needed. So I think this issue can be closed.
Who can close issues when you are gone?

**Comment by ghost** [comment]
Bhante, can you send me a copy of Nathan's email of 1/3/204 that you are referring to? Nathan is asking for it to refresh his memory.
