### ISSUE TITLE
Translated Division and Sub-Division Views

### ISSUE THREAD

**Issue by jhanarato** [suttacentral/legacy-suttacentral#74]
If the language of the user is set, we should display the translated view for divisions. This will have the following columns:

Identifier: As currently shown.
Title: Translated into the user's language and hyperlinked to the translated text.
Description: This is new... will get it's own issue.
Details: As currently for Parallels but without acronyms (just show a triangle)

**Comment by jhanarato** [comment]
Ok, time for a full use-case. 
- A user requests a translated division or subdivision view. This could be by entering a URL directly or by clicking a link from another translated page. 
- The page always loads, provided the division or subdivision requested exists.
- Display the list of suttas for the division/sub-division. 
- The new sutta view will display the identifier, the name of the sutta, a description of the sutta and a green triangle linking to the untranslated sutta details page.
- The sutta name is translated according to the rule below. If there is a translation of the sutta text available the sutta name is hyperlinked to the sutta text, otherwise it is not hyperlinked.
- The sutta name is discovered so: If it exists in the TIM (that is, Nandiya's code slurps up a lot of information about the texts into an in memory model) we use that name. If it is not in the TIM, we check the names.csv file. If it is not found there we provide the name in it's original language (e.g./ Pali). 
- It may be possible to assume that if the name is in TIM then the text exists and we can link the page.
- A consideration: If the name exists in both the TIM and names.csv, then we may end up with "shadowing". That is, if the name in the CSV and TIM are different, then we will never actually show the CSV version, which could trip people. Given that we have the information already in the TIM, what should we store in the CSV file?

**Comment by jhanarato** [comment]
I will wait on Bhante Sujato to have a look at this use-case and to provide a template for the new views.

**Comment by sujato** [comment]
Discussions on i18n have proceeded, i will close this as archaic.
