### ISSUE TITLE
Severe performance degradation when Development bar is enabled

### ISSUE THREAD

**Issue by blake-sc** [suttacentral/legacy-suttacentral#75]
Presently there seems to be some connectivity issues with github with perhaps only 1 in 5 pulls (or other attempts to connect with github) succeeding. This results in most pages at staging.suttacentral.net taking 15s or more to load (sometimes over a minute). Since this is unacceptable even for testing purposes I have for now disabled the development bar in the config file.

**Comment by sujato** [comment]
Who cares?
