### ISSUE TITLE
Specify i18n data files.

### ISSUE THREAD

**Issue by jhanarato** [suttacentral/legacy-suttacentral#77]
I'm suggesting the following:
- **names.csv**: A file containing translations for Pitikas, Collections, Divisions, Sub-Divisions, Vaggas, and Suttas. Other nameables may be added if they fit the theme. The entries in here will be ignored if they already exist in the TIM.
- **descriptions.csv**: Descriptions of pretty much everything and translations of the descriptions for eadh language. This information is not in the TIM.
- **literals.csv**: String literals with their translations. I'm longing to write a function: get_literal_translation() just to confuse people.

**Comment by sujato** [comment]
outdated.
