### ISSUE TITLE
quotehanger: some bugs

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#81]
A couple of things for quotehanger:
1. It fails when there are too many `<a>` tags at the start of the paragraph; this is in fact most of the Pali texts.
2. A more marginal fail: `<br>\n“`. This occurs occasionally in the verses, eg /en/snp5.14

For a perfect storm of bugs, see:

https://suttacentral.net/pi/snp1.3

Each of the first three verses has the quotes at a different place!

**Comment by sujato** [comment]
Bump, perhaps @SamaneriVimala  could check this.

**Comment by ghost** [comment]
Interesting: I don't see the first 3 verses in snp1.3 with different quotes. Only the second one is wrong. See attached screenshot.
![screenshot from 2016-08-17 14-23-58](https://cloud.githubusercontent.com/assets/7444824/17754058/a1656402-6487-11e6-927f-b2c5e30de6a9.png)

> It fails when there are too many <a> tags at the start of the paragraph; this is in fact most of the Pali texts.

The number of `<a>` tags doesn't seem to be the problem. There was a hidden `&shy;` between the quote and the "S". I've fixed this for snp1.3.
@blake-sc: any tip on how to do a regex on `&shy;` using a text editor? \u00AD or \x00AD does not work. Or should I use python?

> A more marginal fail: `<br>\n“`. This occurs occasionally in the verses, eg /en/snp5.14

This is not a fail: this was never programmed to be there. The program only looks for the first character after the `<p>` tag. I'll see what I can do.

**Comment by sujato** [comment]
Great, that looks good to me know. I'll post here if I come across any other cases.

**Comment by ghost** [comment]
Fine, but do you still want me to change the js with regards to cases after a `<br>\n`?

**Comment by sujato** [comment]
That would be good, thanks.

probably not useful, but there are a number of JS libraries that handle this.
- https://github.com/kennethormandy/hanging-punctuation 
- http://boldewyn.github.io/jQuery.exdent/
- https://blot.im/typeset/

The last one is probably too rich for us, it does too many things. The middle one is maybe too simple. The first one seems "just right". What it does, which we don't, is handle quotes in the middle of paragraphs. To do this you have to use a pair of spans to push and pull the margins at the same time. Maybe this is overkill, but anyway, I thought I'd mention it.

**Comment by blake-sc** [comment]
Hmmm, exdent may actually be usable. If it works it'll only take 5 minutes to hook it in.

**Comment by sujato** [comment]
Hang off for now, I have emailed David to ask about the cool option, programming them in open type: https://cirw.in/blog/smart-quotes 

If this works it could simply the JS and the CSS, and heck, might even work in LaTeX too.

**Comment by blake-sc** [comment]
Nice idea, but we also use quotehanger for chinese punctuation and such.

**Comment by sujato** [comment]
Still, the opentype programming doesn't look that hard, if it works we could do it for the Noto fonts as well. I mean, it may well not work, but it won't hurt to wait a few days.

Note that the opentype approach, as well as the first and second options above, give superior typography as compared with quotehanger and exdent. Exdent and quotehanger only apply to the beginning of the line. The other js tools above, and the opentype approach, also work for quotes in the middle of a paragraph. This is a marginal improvement, as it doesn't happen all that often (and when it does happen, it's typically nested quotes, i.e. single quotes, so it doesn't disrupt the line so much.) I'm not that enthused about the js approach for this; it seems to me overly expensive and complicated. But the opentype approach might well be ideal.

**Comment by sujato** [comment]
Just to note, using opentype doesn't work robustly, support is ragged.

**Comment by aminah-sc** [comment]
Not valid on the new site.
