### ISSUE TITLE
text indexing not always correct

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#84]
There are some edge cases where the text numbering does not agree with the data.

See, eg. AN3.156, AN 3.157-161. That's how the numbers appear in the subdivision view. But in the text files we have AN 3.156-162. So currently the text links in the subdivision view don't work. You can only get to that text by entering the URL or by using the next/prev. 

Note that in general I have made the text files of the translations agree with the text files of the Pali, so this problem will be reflected in the translations also. So it is probably not a good idea to solve this by changing the text files.

A solution would be to say that the same text file should show up for both AN3.156 and AN3.157-162. 

There are other cases, and given that it is an edge context, it's likely that they are not identical situations. We should find and fix all cases where the Pali data numbers don't match up with the relevant text files.

**Comment by palistudent** [comment]
Dear Bhante,Thanks for pointing this out.I think the best solution in this particular case is to simply delete the entry for sutta AN 3.156 and rename the other one AN 3.156-162, which should then point to the appropriate 3.156-162 Pali text. This works fine in this case. In other cases, there may be situations where one part of the edge case is a sutta or sutta range that has parallels whereas the other part of it doesn't. In these cases the Pali texts should be split to match, and any translations where possible.
While checking out this issue, I noticed that in neither  case was any Pali text link appearing. Also, I looked at the link to the Sister Upalavanna English translation and got some other website entirely. I don't know whether this is happening with other SU translations from mettanet.
John

```
  From: sujato <notifications@github.com>
```

 To: suttacentral/suttacentral suttacentral@noreply.github.com 
 Sent: Sunday, 19 April 2015, 16:28
 Subject: [suttacentral] text indexing not always correct (#84)

There are some edge cases where the text numbering does not agree with the data.See, eg. AN3.156, AN 3.157-161. That's how the numbers appear in the subdivision view. But in the text files we have AN 3.156-162. So currently the text links in the subdivision view don't work. You can only get to that text by entering the URL or by using the next/prev. Note that in general I have made the text files of the translations agree with the text files of the Pali, so this problem will be reflected in the translations also. So it is probably not a good idea to solve this by changing the text files.A solution would be to say that the same text file should show up for both AN3.156 and AN3.157-162. There are other cases, and given that it is an edge context, it's likely that they are not identical situations. We should find and fix all cases where the Pali data numbers don't match up with the relevant text files.—

**Comment by sujato** [comment]
I'm not sure whether this still applies, @SamaneriVimala to check.

**Comment by ghost** [comment]
With the new json structure this will all be different again anyway.
But in the specific case you mention, file an3.156-162 shows up whichever link you use (an3.156 also works when you just type it as a url)

**Comment by sujato** [comment]
Okay, fine, let's close it.
