### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#87]
No real ideas, just that it would be good to research the best practices for accessibility for websites and implement them as best we can. Given our nice clean, well-structured HTML, it shouldn't be too hard to ensure that blind users and others can access us.

***

As our upgrade proceeds, i would like to bump this issue. We should ensure that the revised site complies with major accessibility guidelines. There's a bunch of web tools around these days to help with that.

A long list here:

https://www.w3.org/WAI/ER/tools/

A more filtered list here:

http://usabilitygeek.com/10-free-web-based-web-site-accessibility-evaluation-tools/

As a general rule, i would propose that any adding of invisible elements to aid accessibility—metadata, etc.—is fine, but anything that requires changes to appearance or function, please run it by me first.

**Comment by aminah-sc** [comment]
Relevant to the new site?

**Comment by aminah-sc** [comment]
Supplanted by the newer accessibility epic: https://github.com/suttacentral/suttacentral/issues/870
