### ISSUE TITLE
Add texts

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#92]
While we have a huge number of texts now on SC, our collection is far from complete. We should keep an eye out for updated or missing texts. 

One major lacuna is the Vietnamese texts, of which we have only a small portion online. In addition, for several collections, such as Thai, Burmese, etc. there is a whole canon and we only have the suttas.

**Comment by ghost** [comment]
I will email around to some Vietnamese and Burmese friends / nuns to see if they have something. I have no contacts in Thailand but could ask at Amaravati.
Also, the people in Dhamma Dvara will have a look out for what what languages they have the Satipatthana in as well as a Farsi speaker to look at the Farsi text.

**Comment by sujato** [comment]
No need to contact people, we have the texts and contacts, just not the work done.

**Comment by ghost** [comment]
Summary of what is going on with adding new texts at the moment:
French - Alain - is working on texts and Vimala to check & upload when finished
Polish - Pjotr - is working on texts and Vimala to check & upload when finished
Norwegian - Vimala/Kare - Thag/Thig to be coded and more on website to check out and code.
Vietnamese - Vimala - lots of stuff from Bhante that needs to be looked at
Burmese - Nathan - KN is ready and needs to be checked/coded by Vimala
Sri Lankan - Janaka -  is working on texts and Vimala need to check & upload when finished (see email and issue 123)
Bengali - Ven Karuna Bangsha  is working on texts but need some work with regards to fonts (see email and issue 121 on Bengali texts).
Japanese - Sarah / Jackie - Sarah to get copyrights, then Vimala or Blake to extract from website and code. (see email and issue 122 on Japanese texts)
Thai - Dheerayupa - is working on texts and Vimala to check & upload when finished (email and issue 124)
Hindi - Dilbag - is working on texts and Vimala to check & upload when finished (email and issue 126)
